import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.webmanifest'), 'utf8'));
const sw = readFileSync(join(ROOT, 'service-worker.js'), 'utf8');
const pwaJs = readFileSync(join(ROOT, 'assets/js/pwa.js'), 'utf8');
const indexHtml = readFileSync(join(ROOT, 'index.html'), 'utf8');
const mainJs = readFileSync(join(ROOT, 'assets/js/main.js'), 'utf8');

/** Manifest validity (spec §9). */
test('manifest.webmanifest is valid JSON with all required fields', () => {
  for (const field of ['name', 'short_name', 'start_url', 'scope', 'display', 'background_color', 'theme_color', 'icons']) {
    assert.ok(field in manifest, `manifest missing ${field}`);
  }
});

test('manifest base path works under /aichatbot/ (absolute paths)', () => {
  assert.equal(manifest.scope, '/aichatbot/');
  assert.equal(manifest.start_url, '/aichatbot/?source=pwa');
  assert.ok(manifest.id === '/aichatbot/');
  for (const icon of manifest.icons) {
    assert.ok(icon.src.startsWith('/aichatbot/'), `icon src must be absolute under /aichatbot/: ${icon.src}`);
  }
});

test('manifest PWA source label tracks the distribution channel (source=pwa)', () => {
  assert.ok(manifest.start_url.includes('source=pwa'));
});

test('manifest icons: svg committed now; png rasters generated by tools/gen-icons.py (CI)', () => {
  const bySrc = Object.fromEntries(manifest.icons.map((i) => [i.src.split('/').pop(), i]));
  assert.ok(bySrc['icon.svg'], 'svg icon entry required');
  assert.ok(existsSync(join(ROOT, 'assets/icons/icon.svg')), 'svg icon file must exist');
  assert.ok(bySrc['icon-192.png'] && bySrc['icon-512.png'] && bySrc['icon-maskable-512.png'],
    'png entries (192/512/maskable) required for Chrome installability');
  assert.equal(bySrc['icon-192.png'].sizes, '192x192');
  assert.equal(bySrc['icon-512.png'].sizes, '512x512');
  assert.equal(bySrc['icon-maskable-512.png'].purpose, 'maskable');
  // PNG rasters are generated deterministically by gen-icons.py (CI commits them).
  assert.ok(existsSync(join(ROOT, 'tools/gen-icons.py')), 'icon generator must exist');
  // Once a png exists (post-CI), it must be a real PNG.
  for (const png of ['icon-192.png', 'icon-512.png', 'icon-maskable-512.png']) {
    const p = join(ROOT, 'assets/icons', png);
    if (existsSync(p)) {
      assert.equal(readFileSync(p).subarray(0, 8).toString('hex'), '89504e470d0a1a0a', `${png} is not a valid PNG`);
    }
  }
});

/** Service worker contract (spec §10). */
test('service worker uses versioned cache names', () => {
  assert.match(sw, /const CORE_VERSION = 'v\d+'/);
  assert.match(sw, /const SHELL_CACHE = 'motoai-shell-' \+ CORE_VERSION/);
  assert.match(sw, /const DATA_CACHE = 'motoai-data-' \+ CORE_VERSION/);
  const major = readFileSync(join(ROOT, 'package.json'), 'utf8');
  const v = JSON.parse(major).version.split('.')[0];
  assert.ok(sw.includes(`'v${v}'`), `cache version tracks core version (v${v})`);
});

test('service worker implements safe cache cleanup on activate', () => {
  assert.match(sw, /addEventListener\('activate'/);
  assert.match(sw, /startsWith\('motoai-'\)/);
  assert.match(sw, /caches\.delete/);
  assert.match(sw, /KNOWN_CACHES/);
});

test('service worker NEVER precaches LLM/embedding models', () => {
  const precache = sw.match(/const SHELL_ASSETS = \[([\s\S]*?)\]/)?.[1] ?? '';
  for (const forbidden of ['webllm', 'transformers', 'model', '.wasm', 'huggingface', 'mlc-ai']) {
    assert.ok(!precache.toLowerCase().includes(forbidden), `precache list must not include ${forbidden}`);
  }
  // Cross-origin requests (where model shards live) are pure passthrough.
  assert.match(sw, /url\.origin !== self\.location\.origin\) return;/);
  assert.match(sw, /WebLLM\/transformers[\s\S]*model shards are managed by the browser/);
});

test('service worker cache strategy: data network-first, shell cache-first + revalidate', () => {
  assert.match(sw, /mode === 'navigate'/);
  assert.match(sw, /caches\.match\(request\)\.then\(\(cached\)/);
  assert.match(sw, /isDataAsset/);
  assert.match(sw, /data\/business\//);
});

/** Offline mode (spec §11) + direct-mode regression (spec §24). */
test('service worker registration only in direct/PWA mode (embed never registers)', () => {
  assert.match(pwaJs, /if \(config\?\.embed\) return/);
  assert.match(pwaJs, /serviceWorker' in navigator/);
  assert.match(pwaJs, /navigator\.serviceWorker\.register\('\.\/service-worker\.js'\)/);
  assert.match(pwaJs, /window\.addEventListener\('load', \(\) => \{/);
  // main.js wires initPwa with the parsed config.
  assert.match(mainJs, /import \{ initPwa \} from '\.\/pwa\.js'/);
  assert.match(mainJs, /initPwa\(config\)/);
});

test('direct app links the manifest + theme-color, embed users unaffected', () => {
  assert.match(indexHtml, /<link rel="manifest" href="manifest\.webmanifest">/);
  assert.match(indexHtml, /<meta name="theme-color" content="#4f46e5">/);
  // Embed iframe loads the same index.html — the SW registration guard keeps it inert.
  assert.match(pwaJs, /config\?\.embed/);
});

/** Install UI (spec §12). */
test('install UI: subtle, beforeinstallprompt-gated, never nagging', () => {
  assert.match(pwaJs, /beforeinstallprompt/);
  assert.match(pwaJs, /event\.preventDefault\(\)/);
  assert.match(pwaJs, /button\.hidden = (true|false)/);
  assert.match(indexHtml, /id="motoai-install"[^>]*hidden/);
  assert.match(pwaJs, /appinstalled/);
  assert.match(pwaJs, /deferredPrompt = null;\s*\n\s*button\.hidden = true;/);
});

test('iOS Add to Home Screen documented hint, shown once (localStorage flag)', () => {
  assert.match(pwaJs, /iP\(hone\|od\|ad\)/);
  assert.match(pwaJs, /motoai:ios-install-hint-shown/);
  assert.match(pwaJs, /Thêm vào Màn hình chính/);
});

test('no API keys / inference endpoints in PWA layer (no-API guarantee)', () => {
  for (const text of [sw, pwaJs, JSON.stringify(manifest)]) {
    for (const key of ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'GEMINI_API_KEY', 'MISTRAL_API_KEY']) {
      assert.ok(!text.includes(key), `PWA layer must not contain ${key}`);
    }
    for (const endpoint of ['api.openai.com', 'api.anthropic.com', 'api.mistral.ai', 'generativelanguage.googleapis.com']) {
      assert.ok(!text.includes(endpoint), `PWA layer must not reference ${endpoint}`);
    }
  }
});
